name: tftapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.1
  collection: ^1.17.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  firebase_core: ^2.22.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_markdown: ^0.6.18+2
  flutter_riverpod: ^2.4.5
  font_awesome_flutter: ^10.6.0
  go_router: ^12.1.0
  google_nav_bar: ^5.0.6
  intl: ^0.18.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/icon1024.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/

    - assets/tft-champions/
    - assets/tft-item/
    - assets/tft-augment/
    - assets/tft-regalia/
    - assets/tft-trait/

  fonts:
    - family: ReadexPro
      fonts:
        - asset: assets/fonts/ReadexPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/ReadexPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/ReadexPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ReadexPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/ReadexPro-Light.ttf
          weight: 300
